// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:aaliyahs_collection_estore/util/config/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVb-0DI8qfyBaRKZa89emaydoqbHBBATQ',
    appId: '1:867637966430:web:e49eab6b2ad45a8f35e6cf',
    messagingSenderId: '867637966430',
    projectId: 'modest-fashion-app',
    authDomain: 'modest-fashion-app.firebaseapp.com',
    storageBucket: 'modest-fashion-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbJeyPHwQXkDE6H4TdcOz5fw6n1YH-IkY',
    appId: '1:867637966430:android:f24f04f08fbdf92d35e6cf',
    messagingSenderId: '867637966430',
    projectId: 'modest-fashion-app',
    storageBucket: 'modest-fashion-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzBW-A4b1X9FN08RoI_MVlfIf9Teb5bKE',
    appId: '1:867637966430:ios:cbe8c4456613785335e6cf',
    messagingSenderId: '867637966430',
    projectId: 'modest-fashion-app',
    storageBucket: 'modest-fashion-app.firebasestorage.app',
    iosBundleId: 'com.example.aaliyahsCollectionEstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzBW-A4b1X9FN08RoI_MVlfIf9Teb5bKE',
    appId: '1:867637966430:ios:cbe8c4456613785335e6cf',
    messagingSenderId: '867637966430',
    projectId: 'modest-fashion-app',
    storageBucket: 'modest-fashion-app.firebasestorage.app',
    iosBundleId: 'com.example.aaliyahsCollectionEstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVb-0DI8qfyBaRKZa89emaydoqbHBBATQ',
    appId: '1:867637966430:web:d5be895b6baddec535e6cf',
    messagingSenderId: '867637966430',
    projectId: 'modest-fashion-app',
    authDomain: 'modest-fashion-app.firebaseapp.com',
    storageBucket: 'modest-fashion-app.firebasestorage.app',
  );
}
